from django.urls import path
from accounts.views import *


app_name = 'accounts'

urlpatterns = [
    path(
        "users/",
        UserListView.as_view(),
        name='users'
    ),
    path(
        "user/<uuid:pk>/",
        UserRetrieveUpdateView.as_view(),
        name='user'
    ),
    path(
        "education/educations/",
        EducationListCreateView.as_view(),
        name='educations'
    ),
    path(
        "education/education/<int:pk>/",
        EducationRetrieveUpdateDestroyView.as_view(),
        name='education'
    ),
    path(
        "education/universities/",
        UniversityListCreateView.as_view(),
        name='universities'
    ),
    path(
        "education/university/<int:pk>/",
        UniversityRetrieveUpdateDestroyView.as_view(),
        name='university'
    ),
    path(
        "education/speciality/<int:pk>/",
        SpecialityRetrieveUpdateDestroyView.as_view(),
        name='speciality'
    ),
    path(
        "education/specialities/",
        SpecialityListCreateView.as_view(),
        name='speciality'
    ),
    path(
        "profile/clients/",
        ClientProfileListView.as_view(),
        name='client-profiles'
    ),
    path(
        "profile/client/<str:pk>/",
        ClientProfileRetrieveUpdateView.as_view(),
        name='client-profile'
    ),
    path(
        "profile/experts/",
        ExpertProfileListView.as_view(),
        name='expert-profiles'
    ),
    path(
        "profile/expert/<slug:pk>/",
        ExpertProfileRetrieveUpdateView.as_view(),
        name='expert-profile'
    ),
    path(
        "subscriptions/",
        SubscriptionPlanListCreateView.as_view(),
        name='subscriptions'
    ),
    path(
        "subscription/<int:pk>/",
        SubscriptionPlanRetrieveUpdateDestroyView.as_view(),
        name='subscription'
    ),
    path(
        "contracts/",
        TherapyContractCreateListView.as_view(),
        name='contracts'
    ),
    path(
        "contract/<int:pk>/",
        TherapyContractRetrieveUpdateView.as_view(),
        name='contract'
    )
]
