# Generated by Django 5.1.6 on 2025-05-16 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_clientprofile_date_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.SlugField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningDimension',
            fields=[
                ('id', models.SlugField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='screening.screening')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='screening.screeningdimension')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='screening.screening')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_response', to='screening.screeninganswer')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screening_response', to='accounts.clientprofile')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_response', to='screening.screeningquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResultInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_possible_results', to='screening.screening')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screening_results', to='accounts.clientprofile')),
                ('result_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screening_result_info', to='screening.screeningresultinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_entries', to='accounts.clientprofile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='screening.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='screening.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='screening.surveyresult')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='screening.surveytheme')),
            ],
        ),
        migrations.AddIndex(
            model_name='screeningquestion',
            index=models.Index(fields=['screening', 'dimension'], name='screening_s_screeni_b982cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screeningquestion',
            unique_together={('screening', 'dimension')},
        ),
        migrations.AddIndex(
            model_name='screeningresponse',
            index=models.Index(fields=['client', 'question'], name='screening_s_client__4aa404_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screeningresponse',
            unique_together={('client', 'question')},
        ),
        migrations.AddIndex(
            model_name='screeningresultinfo',
            index=models.Index(fields=['screening', 'min_score', 'max_score'], name='screening_s_screeni_df2a6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screeningresultinfo',
            unique_together={('screening', 'min_score', 'max_score')},
        ),
        migrations.AddIndex(
            model_name='surveyresult',
            index=models.Index(fields=['client', 'survey'], name='screening_s_client__c4944e_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyentry',
            index=models.Index(fields=['theme', 'result'], name='screening_s_theme_i_095339_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyentry',
            unique_together={('theme', 'result')},
        ),
    ]
