# Generated by Django 5.1.6 on 2025-05-18 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Questionary Category',
                'verbose_name_plural': 'Questionary Categories',
            },
        ),
        migrations.CreateModel(
            name='QuestionaryDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Questionary Dimension',
                'verbose_name_plural': 'Questionary Dimensions',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
            },
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionaries', to='screening.questionarycategory')),
            ],
            options={
                'verbose_name': 'Questionary',
                'verbose_name_plural': 'Questionaries',
            },
        ),
        migrations.CreateModel(
            name='QuestionaryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='screening.questionarydimension')),
                ('questionary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='screening.questionary')),
            ],
            options={
                'verbose_name': 'Questionary Question',
                'verbose_name_plural': 'Questionary Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionaryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='screening.questionaryquestion')),
            ],
            options={
                'verbose_name': 'Questionary Answer',
                'verbose_name_plural': 'Questionary Answers',
            },
        ),
        migrations.CreateModel(
            name='QuestionaryResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scores', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionary_results', to='accounts.clientprofile')),
                ('questionary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionary_results', to='screening.questionary')),
            ],
            options={
                'verbose_name': 'Questionary Result',
                'verbose_name_plural': 'Questionary Results',
            },
        ),
        migrations.CreateModel(
            name='QuestionaryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionary_response', to='screening.questionaryanswer')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionary_response', to='accounts.clientprofile')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionary_response', to='screening.questionaryquestion')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionary_response', to='screening.questionaryresult')),
            ],
            options={
                'verbose_name': 'Questionary Response',
                'verbose_name_plural': 'Questionary Responses',
            },
        ),
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_entries', to='accounts.clientprofile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='screening.survey')),
            ],
            options={
                'verbose_name': 'Survey Result',
                'verbose_name_plural': 'Survey Results',
            },
        ),
        migrations.CreateModel(
            name='SurveyTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='screening.survey')),
            ],
            options={
                'verbose_name': 'Survey Theme',
                'verbose_name_plural': 'Survey Themes',
            },
        ),
        migrations.CreateModel(
            name='SurveyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='screening.surveyresult')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='screening.surveytheme')),
            ],
            options={
                'verbose_name': 'Survey Entry',
                'verbose_name_plural': 'Survey Entries',
            },
        ),
        migrations.AddIndex(
            model_name='questionaryquestion',
            index=models.Index(fields=['questionary', 'dimension'], name='screening_q_questio_43ad41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionaryquestion',
            unique_together={('questionary', 'dimension')},
        ),
        migrations.AddIndex(
            model_name='questionaryresponse',
            index=models.Index(fields=['client', 'question'], name='screening_q_client__2b5001_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionaryresponse',
            unique_together={('client', 'question')},
        ),
        migrations.AddIndex(
            model_name='surveyresult',
            index=models.Index(fields=['client', 'survey'], name='screening_s_client__c4944e_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyentry',
            index=models.Index(fields=['theme', 'result'], name='screening_s_theme_i_095339_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyentry',
            unique_together={('theme', 'result')},
        ),
    ]
