# Generated by Django 5.2.1 on 2025-05-23 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaryresult',
            name='scores',
        ),
        migrations.AlterField(
            model_name='questionaryresult',
            name='questionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='screening.questionary'),
        ),
        migrations.CreateModel(
            name='QuestionaryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=100)),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='screening.questionarydimension')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionaryDimensionScore',
        ),
        migrations.AddField(
            model_name='questionaryresult',
            name='scores',
            field=models.ManyToManyField(related_name='results', to='screening.questionaryscore'),
        ),
    ]
