# Generated by Django 5.2.1 on 2025-05-29 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaryresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
