# Generated by Django 5.2.1 on 2025-05-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionaryresponse',
            options={'verbose_name': 'Questionary Response', 'verbose_name_plural': 'Questionary Responses'},
        ),
        migrations.AddField(
            model_name='questionaryscore',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
