# Generated by Django 5.2.1 on 2025-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaryresponse',
            name='answers',
            field=models.ManyToManyField(blank=True, to='screening.questionaryanswer'),
        ),
    ]
