# Generated by Django 5.2.1 on 2025-05-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_alter_questionaryresponse_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaryAnswerValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name': 'Questionary Answer Value',
                'verbose_name_plural': 'Questionary Answer Values',
            },
        ),
        migrations.RemoveIndex(
            model_name='questionaryanswer',
            name='screening_q_questio_000f49_idx',
        ),
        migrations.AlterUniqueTogether(
            name='questionaryanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questionaryanswervalue',
            name='dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='screening.questionarydimension'),
        ),
        migrations.AddField(
            model_name='questionaryanswer',
            name='values',
            field=models.ManyToManyField(to='screening.questionaryanswervalue'),
        ),
        migrations.RemoveField(
            model_name='questionaryanswer',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='questionaryanswer',
            name='value',
        ),
        migrations.AddIndex(
            model_name='questionaryanswervalue',
            index=models.Index(fields=['dimension', 'value'], name='screening_q_dimensi_852e72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionaryanswervalue',
            unique_together={('dimension', 'value')},
        ),
    ]
