# Generated by Django 5.2.1 on 2025-05-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_remove_questionaryresult_scores_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='questionaryquestion',
            name='screening_q_questio_43ad41_idx',
        ),
        migrations.AlterUniqueTogether(
            name='questionaryquestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questionaryanswer',
            name='dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='screening.questionarydimension'),
        ),
        migrations.AlterUniqueTogether(
            name='questionaryanswer',
            unique_together={('question', 'dimension')},
        ),
        migrations.AddIndex(
            model_name='questionaryanswer',
            index=models.Index(fields=['question', 'dimension'], name='screening_q_questio_000f49_idx'),
        ),
        migrations.RemoveField(
            model_name='questionaryquestion',
            name='dimension',
        ),
    ]
