# Generated by Django 5.2.1 on 2025-06-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_questionaryresponse_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionary',
            options={'ordering': ('title',), 'verbose_name': 'Questionary', 'verbose_name_plural': 'Q - Questionaries'},
        ),
        migrations.AlterModelOptions(
            name='questionaryscoreextra',
            options={'ordering': ('title',), 'verbose_name': 'Score Extra', 'verbose_name_plural': 'Q - Extras'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Survey', 'verbose_name_plural': 'S - Surveys'},
        ),
        migrations.AddField(
            model_name='questionaryresponse',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionaryresponse',
            name='scores',
            field=models.ManyToManyField(blank=True, to='screening.questionaryscore'),
        ),
        migrations.AddField(
            model_name='questionaryresponse',
            name='scores_extra',
            field=models.ManyToManyField(blank=True, to='screening.questionaryscoreextra'),
        ),
    ]
