# Generated by Django 5.2.1 on 2025-05-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_remove_questionaryquestion_screening_q_questio_43ad41_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionaryscore',
            options={'verbose_name': 'Questionary Score', 'verbose_name_plural': 'Questionary Scores'},
        ),
        migrations.AlterField(
            model_name='questionaryresponse',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='responses', to='screening.questionaryanswer'),
        ),
    ]
