# Generated by Django 5.2.1 on 2025-05-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_questionaryanswervalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='category',
        ),
        migrations.AddField(
            model_name='questionary',
            name='categories',
            field=models.ManyToManyField(blank=True, to='screening.categoryquestionary'),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='screening.tagscreening'),
        ),
    ]
