# Generated by Django 5.2.1 on 2025-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_questionaryanswervalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='categoryquestionary',
            options={'verbose_name': 'Category Questionary', 'verbose_name_plural': 'Q - Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorysurvey',
            options={'verbose_name': 'Category Survey', 'verbose_name_plural': 'S - Categories'},
        ),
        migrations.AlterModelOptions(
            name='questionaryanswer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Q - Answers'},
        ),
        migrations.AlterModelOptions(
            name='questionaryanswervalue',
            options={'verbose_name': 'Value', 'verbose_name_plural': 'Q - Values'},
        ),
        migrations.AlterModelOptions(
            name='questionarydimension',
            options={'verbose_name': 'Dimension', 'verbose_name_plural': 'Q - Dimensions'},
        ),
        migrations.AlterModelOptions(
            name='questionaryquestion',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Q - Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionaryresponse',
            options={'verbose_name': 'Response', 'verbose_name_plural': 'Q - Responses'},
        ),
        migrations.AlterModelOptions(
            name='questionaryresult',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Q - Results'},
        ),
        migrations.AlterModelOptions(
            name='questionaryscore',
            options={'verbose_name': 'Score', 'verbose_name_plural': 'Q - Scores'},
        ),
        migrations.AlterModelOptions(
            name='surveyentry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'S - Entries'},
        ),
        migrations.AlterModelOptions(
            name='surveyresult',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'S - Results'},
        ),
        migrations.AlterModelOptions(
            name='surveytheme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'S - Themes'},
        ),
        migrations.RemoveField(
            model_name='questionary',
            name='category',
        ),
        migrations.AddField(
            model_name='questionary',
            name='categories',
            field=models.ManyToManyField(blank=True, to='screening.categoryquestionary'),
        ),
        migrations.AddField(
            model_name='survey',
            name='categories',
            field=models.ManyToManyField(blank=True, to='screening.categorysurvey'),
        ),
        migrations.AlterField(
            model_name='questionaryanswervalue',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='questionary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='screening.tagscreening'),
        ),
        migrations.AddField(
            model_name='survey',
            name='tags',
            field=models.ManyToManyField(blank=True, to='screening.tagscreening'),
        ),
    ]
