# Generated by Django 5.2.1 on 2025-05-26 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_diary'),
        ('screening', '0003_alter_questionaryresponse_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaryresponse',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionary_results', to='accounts.clientprofile'),
        ),
    ]
