# Generated by Django 5.2.1 on 2025-05-26 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_alter_questionaryresponse_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaryresponse',
            name='questionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='screening.questionary'),
        ),
    ]
