# Generated by Django 5.2.1 on 2025-05-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_tagscreening_remove_questionary_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionaryanswervalue',
            options={'verbose_name': 'Questionary Value', 'verbose_name_plural': 'Questionary Values'},
        ),
    ]
