# Generated by Django 5.2.1 on 2025-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_alter_questionaryanswervalue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaryresponse',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionaryanswervalue',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
