# Generated by Django 5.2.1 on 2025-05-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0005_questionaryresponse_questionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaryresponse',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionaryresponse',
            name='is_public_expert',
            field=models.BooleanField(default=False),
        ),
    ]
