# Generated by Django 5.2.1 on 2025-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0006_questionaryresponse_is_filled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryquestionary',
            options={'verbose_name': 'Category Questionary', 'verbose_name_plural': 'Q - Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorysurvey',
            options={'verbose_name': 'Category Survey', 'verbose_name_plural': 'S - Categories'},
        ),
        migrations.AlterModelOptions(
            name='questionaryanswer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Q - Answers'},
        ),
        migrations.AlterModelOptions(
            name='questionaryanswervalue',
            options={'verbose_name': 'Value', 'verbose_name_plural': 'Q - Values'},
        ),
        migrations.AlterModelOptions(
            name='questionarydimension',
            options={'verbose_name': 'Dimension', 'verbose_name_plural': 'Q - Dimensions'},
        ),
        migrations.AlterModelOptions(
            name='questionaryquestion',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Q - Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionaryresponse',
            options={'verbose_name': 'Response', 'verbose_name_plural': 'Q - Responses'},
        ),
        migrations.AlterModelOptions(
            name='questionaryresult',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Q - Results'},
        ),
        migrations.AlterModelOptions(
            name='questionaryscore',
            options={'verbose_name': 'Score', 'verbose_name_plural': 'Q - Scores'},
        ),
        migrations.AlterModelOptions(
            name='surveyentry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'S - Entries'},
        ),
        migrations.AlterModelOptions(
            name='surveyresult',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'S - Results'},
        ),
        migrations.AlterModelOptions(
            name='surveytheme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'S - Themes'},
        ),
        migrations.AddField(
            model_name='survey',
            name='categories',
            field=models.ManyToManyField(blank=True, to='screening.categorysurvey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='tags',
            field=models.ManyToManyField(blank=True, to='screening.tagscreening'),
        ),
    ]
