# Generated by Django 5.2.1 on 2025-05-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
