# Generated by Django 5.2.1 on 2025-06-17 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 6, 22), null=True),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 6, 22), null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 6, 22), null=True),
        ),
    ]
