# Generated by Django 5.1.6 on 2025-05-15 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplanduration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapycontract',
            name='client_plan_duration',
        ),
        migrations.RemoveField(
            model_name='therapycontract',
            name='expert_plan_duration',
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='date_start',
            new_name='client_plan_date',
        ),
        migrations.AddField(
            model_name='therapycontract',
            name='client_plan_days',
            field=models.SmallIntegerField(choices=[(0, 'Free'), (1, 'Day'), (7, 'Week'), (14, 'Two weeks'), (30, 'Month'), (90, 'Three months'), (180, 'Half a year'), (360, 'Year'), (999, 'Forever')], default=0),
        ),
        migrations.AddField(
            model_name='therapycontract',
            name='contract_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='therapycontract',
            name='expert_plan_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='therapycontract',
            name='expert_plan_days',
            field=models.SmallIntegerField(choices=[(0, 'Free'), (1, 'Day'), (7, 'Week'), (14, 'Two weeks'), (30, 'Month'), (90, 'Three months'), (180, 'Half a year'), (360, 'Year'), (999, 'Forever')], default=0),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='client_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='accounts.clientprofile'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='expert_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='accounts.expertprofile'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlanDuration',
        ),
    ]
