# Generated by Django 5.1.6 on 2025-03-03 00:01

import accounts.models
import datetime
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('is_expert', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(help_text='User (Required).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'non-binary'), (3, 'transgender'), (4, 'intersex'), (5, 'prefer not to say')], default=5)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('date_birth', models.DateField(blank=True, default=datetime.date(2007, 3, 8), null=True)),
            ],
            options={
                'verbose_name': "Client's Profile",
                'verbose_name_plural': "Clients' Profiles",
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('user', models.OneToOneField(help_text='User (Required).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'non-binary'), (3, 'transgender'), (4, 'intersex'), (5, 'prefer not to say')], default=5)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('date_birth', models.DateField(blank=True, default=datetime.date(2007, 3, 8), null=True)),
            ],
            options={
                'verbose_name': "Staff member's Profile",
                'verbose_name_plural': "Staff members' Profiles",
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.SmallIntegerField(choices=[(0, 'course'), (1, 'undergraduate'), (2, 'specialist'), (3, 'master'), (4, 'postgraduate'), (5, 'doctor')], default=0)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.speciality')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.university')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('user', models.OneToOneField(help_text='User (Required).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=32)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('gender', models.SmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'non-binary'), (3, 'transgender'), (4, 'intersex'), (5, 'prefer not to say')], default=5)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('date_birth', models.DateField(blank=True, default=datetime.date(2007, 3, 8), null=True)),
                ('education_extra', models.TextField(blank=True, max_length=500)),
                ('countries_allowed', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('education', models.ManyToManyField(blank=True, to='accounts.education')),
            ],
            options={
                'verbose_name': "Expert's Profile",
                'verbose_name_plural': "Experts' Profiles",
            },
        ),
    ]
