# Generated by Django 5.1.6 on 2025-04-22 16:07

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=500)),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('owner_type', models.SmallIntegerField(choices=[(0, 'client'), (1, 'expert')], default=0)),
                ('has_diary', models.BooleanField(default=False)),
                ('has_ai', models.BooleanField(default=False)),
                ('has_screening', models.BooleanField(default=False)),
                ('has_dyagnosis', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 4, 27), null=True),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 4, 27), null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 4, 27), null=True),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.SmallIntegerField(choices=[(0, 'light'), (1, 'dark')], default=0)),
                ('has_health_attention', models.BooleanField(default=False)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientprofile')),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
            },
        ),
        migrations.CreateModel(
            name='TherapyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientprofile')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.expertprofile')),
                ('subscriptionClient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractClientPlan', to='accounts.subscriptionplan')),
                ('subscriptionExpert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractExpertPlan', to='accounts.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Therapy Contract',
                'verbose_name_plural': 'Therapy Contracts',
            },
        ),
    ]
