# Generated by Django 5.1.6 on 2025-05-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='owner_type',
            field=models.SmallIntegerField(choices=[(0, 'Client'), (1, 'Expert'), (2, 'Both')], default=2),
        ),
    ]
