# Generated by Django 5.1.6 on 2025-05-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration',
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='client_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_client', to='accounts.clientprofile'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='client_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_client', to='accounts.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='expert_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_expert', to='accounts.expertprofile'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='expert_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_expert', to='accounts.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='therapycontract',
            name='client_plan_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_client', to='accounts.subscriptionplanduration'),
        ),
        migrations.AddField(
            model_name='therapycontract',
            name='expert_plan_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_expert', to='accounts.subscriptionplanduration'),
        ),
    ]
