# Generated by Django 5.1.6 on 2025-04-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan_alter_clientprofile_date_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
    ]
