# Generated by Django 5.1.6 on 2025-05-13 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapycontract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='accounts.clientprofile'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='accounts.expertprofile'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='subscriptionClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_client', to='accounts.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='subscriptionExpert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_expert', to='accounts.subscriptionplan'),
        ),
    ]
