# Generated by Django 5.1.6 on 2025-05-15 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_subscriptionplan_owner_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'default_related_name': 'clientprofile', 'verbose_name': "Client's Profile", 'verbose_name_plural': "Clients' Profiles"},
        ),
        migrations.AlterModelOptions(
            name='expertprofile',
            options={'default_related_name': 'expertprofile', 'verbose_name': "Expert's Profile", 'verbose_name_plural': "Experts' Profiles"},
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='client_subscription_id',
            new_name='client_plan',
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='expert_subscription_id',
            new_name='expert_plan',
        ),
        migrations.AddField(
            model_name='education',
            name='is_medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 5, 20), null=True),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 5, 20), null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 5, 20), null=True),
        ),
    ]
