# Generated by Django 5.1.6 on 2025-05-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_therapycontract_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapycontract',
            name='subscriptionClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_contract', to='accounts.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='subscriptionExpert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_contract', to='accounts.subscriptionplan'),
        ),
    ]
