# Generated by Django 5.1.6 on 2025-05-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_therapycontract_client_plan_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapycontract',
            old_name='client_plan_date',
            new_name='client_plan_start_date',
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='contract_date',
            new_name='contract_start_date',
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='expert_plan_date',
            new_name='expert_plan_start_date',
        ),
    ]
