# Generated by Django 5.1.6 on 2025-05-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_client_plan_date_therapycontract_client_plan_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapycontract',
            old_name='client_plan_start_date',
            new_name='client_plan_prolong_date',
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='expert_plan_start_date',
            new_name='expert_plan_prolong_date',
        ),
    ]
