# Generated by Django 5.1.6 on 2025-05-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_therapycontract_subscriptionclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapycontract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='accounts.clientprofile', to_field='email'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='accounts.expertprofile', to_field='email'),
        ),
    ]
