# Generated by Django 5.1.6 on 2025-05-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_therapycontract_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapycontract',
            old_name='client',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='subscriptionClient',
            new_name='client_subscription',
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='expert',
            new_name='expert_email',
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='subscriptionExpert',
            new_name='expert_subscription',
        ),
    ]
