# Generated by Django 5.1.6 on 2025-05-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_client_plan_start_date_therapycontract_client_plan_prolong_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapycontract',
            old_name='client_email',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='therapycontract',
            old_name='expert_email',
            new_name='expert',
        ),
    ]
