# Generated by Django 5.1.6 on 2025-05-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_client_email_therapycontract_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_medical',
        ),
    ]
