# Generated by Django 5.1.6 on 2025-05-13 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_client_therapycontract_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapycontract',
            name='client_email',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='accounts.clientprofile', to_field='email'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='client_subscription',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_contract', to='accounts.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='expert_email',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='accounts.expertprofile', to_field='email'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='expert_subscription',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='expert_contract', to='accounts.subscriptionplan'),
        ),
    ]
