# Generated by Django 5.1.6 on 2025-05-13 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_therapycontract_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapycontract',
            name='client_email',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='accounts.clientprofile'),
        ),
        migrations.AlterField(
            model_name='therapycontract',
            name='expert_email',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='accounts.expertprofile'),
        ),
    ]
