# Generated by Django 5.1.6 on 2025-05-15 17:20

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_education_is_medical'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14),
        ),
    ]
