# Generated by Django 5.1.6 on 2025-05-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscriptionplan_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.education'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='education_extra',
            field=models.TextField(default='', max_length=500),
        ),
    ]
