# Generated by Django 5.1.6 on 2025-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_expertprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='education',
            field=models.ManyToManyField(blank=True, to='accounts.education'),
        ),
    ]
