# Generated by Django 5.1.6 on 2025-05-16 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_expertprofile_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 5, 21), null=True),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 5, 21), null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_birth',
            field=models.DateField(blank=True, default=datetime.date(2007, 5, 21), null=True),
        ),
    ]
